openapi: "3.0.2"
info:
  title: Account management
  version: "1.0"
servers:
  - url: http://???/v1

components:
  schemas:
    account:
      type: object
      properties:
        saldo:
          type: number
          format: double
        limiteSaqueDiario:
          type: number
          format: double
        flagAtivo:
          type: boolean
        tipoConta:
          type: integer
    create_person:
      type: object
      properties:
        nome:
          type: string
        cpf:
          type: string
        dataNascimento:
          type: string
          format: date
    idPessoa:
      allOf:
        - $ref: "#/components/schemas/create_person"
        - properties:
            id:
              type: integer
    account_existing_person:
      required:
        - idPessoa
        - saldo
        - limiteSaqueDiario
        - flagAtivo
        - tipoConta
      allOf:
        - $ref: "#/components/schemas/account"
        - properties:
            idPessoa:
              type: integer
    account_new_person:
      required:
        - saldo
        - limiteSaqueDiario
        - flagAtivo
        - tipoConta
        - nome
        - cpf
        - dataNascimento
      allOf:
        - $ref: "#/components/schemas/account"
        - $ref: "#/components/schemas/create_person"
    deposit:
      properties:
        value:
          type: number
          minimum: 0
          exclusiveMinimum: true
    account_blocked:
      properties:
        error:
          type: string
          example: Conta esta bloqueada
    deposit_minimum_value:
      properties:
        error:
          type: string
          example: |
            O deposito não pode ser usado para saque na conta. Não e permido valores negativos
paths:
  /account:
    # Implementar path que realiza a criação de uma conta
    post:
      summary: Criação de uma conta, tambem cria pessoa caso informações sejam passadas
      requestBody:
        description: |
          Informações da conta
          Caso pessoa nao existe a hava os dados para criação esse será feito
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/account_new_person"
                - $ref: "#/components/schemas/account_existing_person"
      responses:
        "201":
          description: CREATED
          headers:
            Content-Localtion:
              schema:
                type: string
              description: Path do recurso criado
        "400":
          description: BAD_REQUEST
        "500":
          description: INTERNAL_SERVER_ERROR
  /account/<account_id>/deposit/:
    # Implementar path que realiza operação de depósito em uma conta
    post:
      summary: Executa uma transação para depósito
      requestBody:
        description: Modelo com valor do depósito
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/deposit"
      responses:
        "201":
          description: CREATED
        "400":
          description: BAD_REQUEST
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/deposit_minimum_value"
        "403":
          description: FORBIDDEN
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/account_blocked"
        "404":
          description: NOT_FOUND
  /account/<account_id>/balance/:
    # Implementar path que realiza operação de consulta de saldo em determinada conta
    get:
      summary: Consulta de saldo em determinada conta
      responses:
        "200":
          description: OK
  /account/<account_id>/withdrawal:
    # Implementar path que realiza operação de saque em uma conta
    patch:
      summary: saque em uma conta
      responses:
        "200":
          description: OK
  /account/<account_id>/block:
    # Implementar path que realiza o bloqueio de uma conta
    post:
      summary: bloqueio de uma conta
      responses:
        "200":
          description: OK
  /account/<account_id>/transactions:
    # Implementar path que recupera o extrato de transações de uma conta
    get:
      description: <???>
      summary: extrato de transacoes feita por uma conta
      responses:
        "200":
          description: OK
